"""Domain-appropriate label vocabulary.

Labels are plausible project/business facts rather than lorem ipsum so that the
payloads read like real memory records to the model. Each list holds >= 24
entries, which covers the largest per-domain node count in the sweep (80 nodes
/ 4 domains = 20). Labels are 2-4 words.
"""

from __future__ import annotations

DOMAIN_VOCAB: dict[str, tuple[str, ...]] = {
    "Finance": (
        "Series A closed",
        "Burn rate reduced",
        "Pricing tiers revised",
        "Annual audit completed",
        "Vendor contract renegotiated",
        "Revenue forecast lowered",
        "Cash runway extended",
        "Invoice tooling replaced",
        "Discount policy tightened",
        "Payroll provider switched",
        "Expense caps introduced",
        "Board budget approved",
        "Churn impact modeled",
        "Collections process automated",
        "Tax filing delayed",
        "Bridge note signed",
        "Unit economics reviewed",
        "Procurement freeze lifted",
        "Finance headcount frozen",
        "Quarterly close accelerated",
        "Refund policy clarified",
        "Currency hedging adopted",
        "Capex request denied",
        "Margin targets raised",
    ),
    "Growth": (
        "Paid search paused",
        "Referral program launched",
        "Onboarding funnel redesigned",
        "Trial length shortened",
        "Signup conversion dropped",
        "Content calendar approved",
        "Partner channel added",
        "Email cadence reduced",
        "Landing page rewritten",
        "Attribution model changed",
        "Webinar series cancelled",
        "SEO audit completed",
        "Activation metric redefined",
        "Pricing page tested",
        "Community forum opened",
        "Ad budget reallocated",
        "Lifecycle emails automated",
        "Free tier introduced",
        "Enterprise pilot signed",
        "Waitlist gate removed",
        "Retention cohort improved",
        "Brand refresh shipped",
        "Outbound team disbanded",
        "Demo requests spiked",
    ),
    "People": (
        "Senior SRE hired",
        "Remote policy formalized",
        "Performance cycle skipped",
        "Engineering manager departed",
        "Interview loop shortened",
        "Compensation bands published",
        "Mentorship program started",
        "Contractor budget approved",
        "Hiring freeze announced",
        "Team reorg completed",
        "Oncall rotation expanded",
        "Parental leave extended",
        "Design lead promoted",
        "Recruiting agency dropped",
        "Skip levels introduced",
        "Handbook rewritten",
        "Internship cohort doubled",
        "Attrition spike investigated",
        "Title ladder revised",
        "Offsite budget cut",
        "Support team relocated",
        "Peer review piloted",
        "Headcount plan approved",
        "Onboarding buddies assigned",
    ),
    "Platform": (
        "Postgres migration approved",
        "Kafka cluster upgraded",
        "Latency budget breached",
        "Monolith split started",
        "Feature flags adopted",
        "Region failover tested",
        "Build times halved",
        "Cache layer added",
        "Legacy API deprecated",
        "Terraform modules consolidated",
        "Secrets rotation automated",
        "Staging environment rebuilt",
        "GraphQL gateway shipped",
        "Incident postmortem published",
        "Rate limiting enforced",
        "Observability vendor changed",
        "Schema registry introduced",
        "Blue green deploys",
        "Backup restore verified",
        "Mobile SDK released",
        "Search index rebuilt",
        "Queue backlog cleared",
        "Container runtime swapped",
        "Access control tightened",
    ),
}
